server:
  port: 8081

spring:
  application:
    name: user-service

  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://config-server:8888}

  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/${DB_NAME:user_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  instance:
    prefer-ip-address: true
    # Better removed, fallback added
    ip-address: ${EUREKA_IP:user-service}

  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://eureka-server:8761/eureka/}

app:
  jwt:
    secret: ${JWT_SECRET:default_jwt_secret}
    expiration: ${JWT_EXPIRATION:86400000}

management:
  tracing:
    sampling:
      probability: 1.0

  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL:http://zipkin:9411/api/v2/spans}